version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: otus_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: otus

  redis:
    image: redis:7
    container_name: otus_redis
    ports:
      - "6379:6379"

